//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ID { get; set; }
        public System.DateTime RequestTime { get; set; }
        public string IpOrHost { get; set; }
        public string Routing { get; set; }
        public string AdditionalParam { get; set; }
        public int Result { get; set; }
        public string Location { get; set; }
        public string Size { get; set; }
    }
}
